# Generated by Django 5.2.7 on 2025-11-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField()),
                ('numero', models.IntegerField()),
                ('classe', models.IntegerField()),
                ('sala', models.IntegerField()),
                ('curso', models.CharField(max_length=50)),
                ('ingresso', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
