# Generated by Django 5.2.7 on 2025-11-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='classe',
            field=models.IntegerField(choices=[(10, '10ª Classe'), (11, '11ª Classe'), (12, '12ª Classe'), (13, '13ª Classe')]),
        ),
        migrations.AlterField(
            model_name='propinas',
            name='mes',
            field=models.CharField(max_length=50),
        ),
    ]
