# Generated by Django 5.2.7 on 2025-11-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='turno',
            field=models.CharField(default='Indefinido'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='sala',
            field=models.CharField(),
        ),
    ]
