# Generated by Django 5.2.7 on 2025-11-24 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('registrada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='registrada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('tempo_trabalho', models.TimeField()),
                ('registrado', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('1º', 'Primeiro Trimestre'), ('2º', 'Segundo Trimestre'), ('3º', 'Terceiro Trimestre')], max_length=5)),
                ('prova', models.CharField(choices=[('Avaliação', 'Avaliação Contínua'), ('Prova do professor', 'Prova do Professor'), ('Prova Trimestral', 'Prova do Trimestre')], max_length=100)),
                ('nota', models.IntegerField()),
                ('registrada', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.alunos')),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.disciplinas')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.professores')),
            ],
        ),
    ]
