# Generated by Django 5.2.7 on 2025-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_disciplinas_mensalidade_registrada_professores_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Matrícula', 'Matrícula'), ('Confirmação', 'Confirmação'), ('Propina', 'Propina'), ('Prova', 'Prova'), ('Uniforme', 'Uniforme'), ('Cartão', 'Cartão'), ('Estágio', 'Estágio')], max_length=100)),
                ('mes', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.CharField(max_length=50)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
