# Generated by Django 5.2.7 on 2025-12-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_pagamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='tipo',
            field=models.CharField(choices=[('Matrícula', 'Matrícula'), ('Confirmação', 'Confirmação'), ('Propina', 'Propina'), ('Folha de Prova', 'Folha de Prova'), ('Uniforme Escolar', 'Uniforme Escolar'), ('Uniforme de Ed. Física', 'Uniforme de Ed. Física'), ('Cartão', 'Cartão'), ('Estágio', 'Estágio')], max_length=100),
        ),
    ]
