from django import forms
from .models import Alunos

class Formulario_Cadastro(forms.ModelForm):
    class Meta:
        model = Alunos
        fields = ('nome', 'curso', 'turno', 'numero', 'data_nascimento', 'genero', 'classe', 'sala')

        widgets = {
            'nome' : forms.TextInput(attrs={ 'placeholder' : 'Nome do Aluno' }),
            'curso' : forms.Select(attrs={ 'placeholder' : 'Curso do Aluno', 'class' : 'genero' }, choices=[
                ('Enfermagem', 'Enfermagem'),
                ('Programação', 'Programação'),
                ('Informática', 'Informática'),
                ('Contabilidade', 'Contabilidade'),
                ('Gestão Empresarial', 'Gestão de Empresas'),
                ('Electricidade', 'Electricidade'),
            ]),
            'numero' : forms.NumberInput(attrs={ 'placeholder' : 'Número do Aluno' }),
            'data_nascimento' : forms.DateInput(attrs={'type' : 'date'}),
            'genero' : forms.Select(attrs={ 'placeholder' : 'Genero do Aluno', 'class' : 'genero' }, choices=[
                ('M', 'Masculino'),
                ('F', 'Feminino'),
            ]),
            'turno' : forms.Select(attrs={ 'class' : 'genero' }, choices=[
                ('Manhã', 'Manhã'),
                ('Tarde', 'Tarde'),
            ]),
            'classe' : forms.Select(attrs={ 'class' : 'genero' }, choices=[
                ('10', '10ª Classe'),
                ('11', '11ª Classe'),
                ('12', '12ª Classe'),
                ('13', '13ª Classe'),
            ]),
            'sala' : forms.Select(attrs={ 'class' : 'genero' }, choices=[
                ('1', 'Sala 1 - Enfermagem (10ª Manhã)'),
                ('2', 'Sala 2 - Programação (10ª Manhã)'),
                ('3', 'Sala 3 - Informática (10ª Manhã)'),
                ('4', 'Sala 4 - Contabilidade (10ª Manhã)'),
                ('5', 'Sala 5 - Gestão de Empresas (10ª Manhã)'),
                ('6', 'Sala 6 - Electricidade (10ª Manhã)'),
                ('7', 'Sala 7 - Enfermagem (11ª Manhã)'),
                ('8', 'Sala 8 - Programação (11ª Manhã)'),
                ('9', 'Sala 9 - Informática (11ª Manhã)'),
                ('10', 'Sala 10 - Contabilidade (11ª Manhã)'),
                ('11', 'Sala 11 - Gestão de Empresas (11ª Manhã)'),
                ('12', 'Sala 12 - Electricidade (11ª Manhã)'),
                ('13', 'Sala 7 - Enfermagem (12ª Manhã)'),
                ('14', 'Sala 8 - Programação (12ª Manhã)'),
                ('15', 'Sala 9 - Informática (12ª Manhã)'),
                ('16', 'Sala 10 - Contabilidade (12ª Manhã)'),
                ('17', 'Sala 11 - Gestão de Empresas (12ª Manhã)'),
                ('18', 'Sala 12 - Electricidade (12ª Manhã)'),
                ('19', 'Sala 13 - Enfermagem (13ª Manhã)'),
                ('20', 'Sala 14 - Programação (13ª Manhã)'),
                ('21', 'Sala 15 - Informática (13ª Manhã)'),
                ('22', 'Sala 16 - Contabilidade (13ª Manhã)'),
                ('23', 'Sala 17 - Gestão de Empresas (13ª Manhã)'),
                ('24', 'Sala 18 - Electricidade (13ª Manhã)'),
                ('1', 'Sala 19 - Enfermagem (10ª Tarde)'),
                ('2', 'Sala 20 - Programação (10ª Tarde)'),
                ('3', 'Sala 21 - Informática (10ª Tarde)'),
                ('4', 'Sala 22 - Contabilidade (10ª Tarde)'),
                ('5', 'Sala 23 - Gestão de Empresas (10ª Tarde)'),
                ('6', 'Sala 24 - Electricidade (10ª Tarde)'),
                ('7', 'Sala 25 - Enfermagem (11ª Tarde)'),
                ('8', 'Sala 26 - Programação (11ª Tarde)'),
                ('9', 'Sala 27 - Informática (11ª Tarde)'),
                ('10', 'Sala 10 - Contabilidade (11ª Tarde)'),
                ('11', 'Sala 11 - Gestão de Empresas (11ª Tarde)'),
                ('12', 'Sala 12 - Electricidade (11ª Tarde)'),
                ('13', 'Sala 7 - Enfermagem (12ª Tarde)'),
                ('14', 'Sala 8 - Programação (12ª Tarde)'),
                ('15', 'Sala 9 - Informática (12ª Tarde)'),
                ('16', 'Sala 10 - Contabilidade (12ª Tarde)'),
                ('17', 'Sala 11 - Gestão de Empresas (12ª Tarde)'),
                ('18', 'Sala 12 - Electricidade (12ª Tarde)'),
                ('19', 'Sala 13 - Enfermagem (13ª Tarde)'),
                ('20', 'Sala 14 - Programação (13ª Tarde)'),
                ('21', 'Sala 15 - Informática (13ª Tarde)'),
                ('22', 'Sala 16 - Contabilidade (13ª Tarde)'),
                ('23', 'Sala 17 - Gestão de Empresas (13ª Tarde)'),
                ('24', 'Sala 18 - Electricidade (13ª Tarde)'),
            ]),
        }

class EditeForm(forms.ModelForm):
    class Meta:
        model = Alunos
        fields = ('nome', 'curso', 'turno', 'numero', 'data_nascimento', 'genero', 'classe', 'sala')

        widgets = {
            'nome' : forms.TextInput(attrs={ 'placeholder' : 'Nome do Aluno' }),
            'curso' : forms.Select(attrs={ 'placeholder' : 'Curso do Aluno', 'class' : 'genero' }, choices=[
                ('Enfermagem', 'Enfermagem'),
                ('Programação', 'Programação'),
                ('Informática', 'Informática'),
                ('Contabilidade', 'Contabilidade'),
                ('Gestão Empresarial', 'Gestão de Empresas'),
                ('Electricidade', 'Electricidade'),
            ]),
            'numero' : forms.NumberInput(attrs={ 'placeholder' : 'Número do Aluno' }),
            'data_nascimento' : forms.DateInput(attrs={'type' : 'date'}),
            'genero' : forms.Select(attrs={ 'class' : 'genero' }, choices=[
                ('M', 'Masculino'),
                ('F', 'Feminino'),
            ]),
            'turno' : forms.Select(attrs={ 'class' : 'genero' }, choices=[
                ('Manhã', 'Manhã'),
                ('Tarde', 'Tarde'),
            ]),
            'classe' : forms.Select(attrs={ 'class' : 'genero' }, choices=[
                ('10', '10ª Classe'),
                ('11', '11ª Classe'),
                ('12', '12ª Classe'),
                ('13', '13ª Classe'),
            ]),
            'sala' : forms.Select(attrs={ 'placeholder' : 'Sala do Aluno', 'class' : 'genero'}, choices=[
                ('1', 'Sala 1 - Enfermagem (10ª Manhã)'),
                ('2', 'Sala 2 - Programação (10ª Manhã)'),
                ('3', 'Sala 3 - Informática (10ª Manhã)'),
                ('4', 'Sala 4 - Contabilidade (10ª Manhã)'),
                ('5', 'Sala 5 - Gestão de Empresas (10ª Manhã)'),
                ('6', 'Sala 6 - Electricidade (10ª Manhã)'),
                ('7', 'Sala 7 - Enfermagem (11ª Manhã)'),
                ('8', 'Sala 8 - Programação (11ª Manhã)'),
                ('9', 'Sala 9 - Informática (11ª Manhã)'),
                ('10', 'Sala 10 - Contabilidade (11ª Manhã)'),
                ('11', 'Sala 11 - Gestão de Empresas (11ª Manhã)'),
                ('12', 'Sala 12 - Electricidade (11ª Manhã)'),
                ('13', 'Sala 13 - Enfermagem (12ª Manhã)'),
                ('14', 'Sala 14 - Programação (12ª Manhã)'),
                ('15', 'Sala 15 - Informática (12ª Manhã)'),
                ('16', 'Sala 16 - Contabilidade (12ª Manhã)'),
                ('17', 'Sala 17 - Gestão de Empresas (12ª Manhã)'),
                ('18', 'Sala 18 - Electricidade (12ª Manhã)'),
                ('19', 'Sala 19 - Enfermagem (13ª Manhã)'),
                ('20', 'Sala 20 - Programação (13ª Manhã)'),
                ('21', 'Sala 21 - Informática (13ª Manhã)'),
                ('22', 'Sala 22 - Contabilidade (13ª Manhã)'),
                ('23', 'Sala 23 - Gestão de Empresas (13ª Manhã)'),
                ('24', 'Sala 24 - Electricidade (13ª Manhã)'),
                ('1', 'Sala 1 - Enfermagem (10ª Tarde)'),
                ('2', 'Sala 2 - Programação (10ª Tarde)'),
                ('3', 'Sala 3 - Informática (10ª Tarde)'),
                ('4', 'Sala 4 - Contabilidade (10ª Tarde)'),
                ('5', 'Sala 5 - Gestão de Empresas (10ª Tarde)'),
                ('6', 'Sala 6 - Electricidade (10ª Tarde)'),
                ('7', 'Sala 7 - Enfermagem (11ª Tarde)'),
                ('8', 'Sala 8 - Programação (11ª Tarde)'),
                ('9', 'Sala 9 - Informática (11ª Tarde)'),
                ('10', 'Sala 10 - Contabilidade (11ª Tarde)'),
                ('11', 'Sala 11 - Gestão de Empresas (11ª Tarde)'),
                ('12', 'Sala 12 - Electricidade (11ª Tarde)'),
                ('13', 'Sala 13 - Enfermagem (12ª Tarde)'),
                ('14', 'Sala 14 - Programação (12ª Tarde)'),
                ('15', 'Sala 15 - Informática (12ª Tarde)'),
                ('16', 'Sala 16 - Contabilidade (12ª Tarde)'),
                ('17', 'Sala 17 - Gestão de Empresas (12ª Tarde)'),
                ('18', 'Sala 18 - Electricidade (12ª Tarde)'),
                ('19', 'Sala 19 - Enfermagem (13ª Tarde)'),
                ('20', 'Sala 20 - Programação (13ª Tarde)'),
                ('21', 'Sala 21 - Informática (13ª Tarde)'),
                ('22', 'Sala 22 - Contabilidade (13ª Tarde)'),
                ('23', 'Sala 23 - Gestão de Empresas (13ª Tarde)'),
                ('24', 'Sala 24 - Electricidade (13ª Tarde)'),
            ]),
        }